import Head from 'next/head'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter()

    const linkTest = () => {
    if (router.isReady) {
        router.push("/character");
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => linkTest()}>Link to test page</button>
    </>
  )
}
